if __name__ == '__main__':
	cal1 = float()
	cal2 = float()
	cal3 = float()
	cal4 = float()
	cal5 = float()
	promedio = float()
	print("ingrese las 5 calificaciones")
	cal1 = float(input())
	cal2 = float(input())
	cal3 = float(input())
	cal4 = float(input())
	cal5 = float(input())
	promedio = (cal1+cal2+cal3+cal4+cal5)/5
	print("El promedio de las calificaciones es: ",promedio)
